// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWdykEhpnXZV5xeeGKqStnGh3pzgdlfQk',
    appId: '1:477552302812:web:a3aa07a3ae6b175e86f219',
    messagingSenderId: '477552302812',
    projectId: 'educationbackend-82bf1',
    authDomain: 'educationbackend-82bf1.firebaseapp.com',
    storageBucket: 'educationbackend-82bf1.appspot.com',
    measurementId: 'G-XP7R56RQ7W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtLfsJr_CxCnAx-o2VbL_2SaZQCifbc84',
    appId: '1:477552302812:android:c1b5f32a5da5ae1a86f219',
    messagingSenderId: '477552302812',
    projectId: 'educationbackend-82bf1',
    storageBucket: 'educationbackend-82bf1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvwBP4ThW2rgamvZLXW_RfQay2d7VJGTs',
    appId: '1:477552302812:ios:67622e4f05ab230386f219',
    messagingSenderId: '477552302812',
    projectId: 'educationbackend-82bf1',
    storageBucket: 'educationbackend-82bf1.appspot.com',
    iosClientId: '477552302812-ne2o5rb2a1mbijka9n4kf53ls8fpnr5n.apps.googleusercontent.com',
    iosBundleId: 'com.example.educationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvwBP4ThW2rgamvZLXW_RfQay2d7VJGTs',
    appId: '1:477552302812:ios:67622e4f05ab230386f219',
    messagingSenderId: '477552302812',
    projectId: 'educationbackend-82bf1',
    storageBucket: 'educationbackend-82bf1.appspot.com',
    iosClientId: '477552302812-ne2o5rb2a1mbijka9n4kf53ls8fpnr5n.apps.googleusercontent.com',
    iosBundleId: 'com.example.educationApp',
  );
}
